import { GeralContext } from "./context/GeralContext"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {

  return (
    <html lang="enpt-br">
      <GeralContext>
        <body>{children}</body>
      </GeralContext>

    </html>
  )
}
